<?php

namespace App\Http\Controllers;

use App\Enums\ChannelLogoType;
use App\Enums\PlaylistChannelId;
use App\Facades\PlaylistFacade;
use App\Models\AedProfile;
use App\Models\CustomPlaylist;
use App\Models\Epg;
use App\Models\MergedPlaylist;
use App\Models\Network;
use App\Models\Playlist;
use App\Models\PlaylistAlias;
use App\Services\AedExtractorService;
use App\Services\EpgCacheService;
use App\Services\EpisodeNumberNormalizer;
use App\Services\NetworkEpgService;
use Carbon\Carbon;
use DOMDocument;
use DOMElement;
use Exception;
use Filament\Notifications\Notification;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use XMLReader;

class EpgGenerateController extends Controller
{
    /**
     * File cache configuration
     */
    private const CACHE_TTL_HOURS = 6; // Cache files for 6 hours

    /**
     * Escape XML text and attribute values using UTF-8 explicitly.
     */
    private function escapeXml(mixed $value): string
    {
        return htmlspecialchars((string) $value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
    }

    /**
     * Generate the EPG XML file
     *
     * @return Response
     */
    public function __invoke(string $uuid)
    {
        // Fetch the playlist
        $playlist = PlaylistFacade::resolvePlaylistByUuid($uuid);
        if (! $playlist) {
            return response()->json(['Error' => 'Playlist Not Found'], 404);
        }

        // Handle network playlists - generate EPG from networks
        if ($playlist instanceof Playlist && $playlist->is_network_playlist) {
            return $this->generateNetworkPlaylistEpg($playlist);
        }

        // Check if we have a valid cached file
        if ($this->isCacheValid($playlist, false)) {
            return $this->serveCachedFile($playlist, false);
        }

        // Generate and cache new file
        return $this->generateAndCache($playlist, false);
    }

    /**
     * Generate the EPG XML file and compress it
     *
     * @return Response
     */
    public function compressed(string $uuid)
    {
        // Fetch the playlist
        $playlist = PlaylistFacade::resolvePlaylistByUuid($uuid);
        if (! $playlist) {
            return response()->json(['Error' => 'Playlist Not Found'], 404);
        }

        // Check if we have a valid cached file
        if ($this->isCacheValid($playlist, true)) {
            return $this->serveCachedFile($playlist, true);
        }

        // Generate and cache new file
        return $this->generateAndCache($playlist, true);
    }

    /**
     * Generate the EPG XML file contents
     *
     * @param  Playlist|MergedPlaylist|CustomPlaylist|PlaylistAlias  $playlist
     */
    private function generate($playlist)
    {
        // Output the XML header
        echo '<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv generator-info-name="Generated by m3u editor" generator-info-url="'.url('').'">';
        echo PHP_EOL;

        // Set up the channels
        $epgChannels = [];
        $dummyEpgChannels = [];
        $channels = PlaylistGenerateController::getChannelQuery($playlist);

        // Pre-load AED profile IDs that have override=true for this playlist's owner
        // so we can short-circuit EPG matching for channels with those profiles assigned
        $overrideAedProfileIds = AedProfile::where('override', true)
            ->where('user_id', $playlist->user_id)
            ->pluck('id')
            ->flip()
            ->all();

        // Get playlist settings
        $channelNumber = $playlist->auto_channel_increment ? $playlist->channel_start - 1 : 0;
        $idChannelBy = $playlist->id_channel_by;
        $dummyEpgEnabled = $playlist->dummy_epg;
        $dummyEpgLength = (int) ($playlist->dummy_epg_length ?? 120); // Default to 120 minutes if not set
        $dummyEpgFallbackOrder = collect($playlist->dummy_epg_fallback_order ?? [])
            ->pluck('method')
            ->filter()
            ->values()
            ->all();
        $proxyEnabled = $playlist->enable_proxy;
        $logoProxyEnabled = $playlist->enable_logo_proxy;

        // Detect custom playlist context (custom playlists store channel numbers in pivot table)
        $isCustomContext = ($playlist instanceof CustomPlaylist)
            || ($playlist instanceof PlaylistAlias && ! empty($playlist->custom_playlist_id));

        // Track network channels for programme output later
        $networkChannelIds = [];

        // Generate `<channel>` tags for each channel
        foreach ($channels->cursor() as $channel) {
            // Track network channels for special programme handling
            if ($channel->network_id) {
                $networkChannelIds[$channel->network_id] = $channel->stream_id ?? 'network-'.$channel->network_id;
            }

            // Get/set the channel number (use pivot channel_number for custom playlists)
            $channelNo = ($isCustomContext && ! empty($channel->pivot?->channel_number))
                ? (int) $channel->pivot->channel_number
                : $channel->channel;
            if (! $channelNo && ($playlist->auto_channel_increment || $idChannelBy === PlaylistChannelId::Number)) {
                $channelNo = ++$channelNumber;
            }

            // Get the `tvg-id` based on the playlist setting
            switch ($idChannelBy) {
                case PlaylistChannelId::ChannelId:
                    $tvgId = $channel->id;
                    break;
                case PlaylistChannelId::Number:
                    $tvgId = $channelNo;
                    break;
                case PlaylistChannelId::Name:
                    $tvgId = $channel->name_custom ?? $channel->name;
                    break;
                case PlaylistChannelId::Title:
                    $tvgId = $channel->title_custom ?? $channel->title;
                    break;
                default:
                    $tvgId = $channel->stream_id_custom ?? $channel->source_id ?? $channel->stream_id;
                    break;
            }

            // Ultimate last resort
            if (empty($tvgId)) {
                $tvgId = $channel->source_id ?? $channel->id;
            }

            // Make sure TVG ID only contains characters and numbers
            $tvgId = preg_replace(config('dev.tvgid.regex'), '', $tvgId);

            // Output the <channel> tag
            $title = $channel->title_custom ?? $channel->title;
            $title = $this->escapeXml($title);

            // Get the EPG channel data
            $epgData = $channel->epgChannel ?? null;

            // Resolve effective AED profile and check for override flag
            $aedProfileId = $channel->aed_profile_id ?? $channel->group_aed_profile_id ?? null;
            $hasAedOverride = $aedProfileId && isset($overrideAedProfileIds[$aedProfileId]);

            // Output the <channel> tag
            if ($epgData && ! $hasAedOverride) {
                // Keep track of which EPGs have which channels mapped
                // Need this to output the <programme> tags later
                if (! array_key_exists($epgData->epg_id, $epgChannels)) {
                    $epgChannels[$epgData->epg_id] = [];
                }
                $epgChannels[$epgData->epg_id][] = [
                    $epgData->channel_id => [
                        'tvg_id' => $tvgId,
                        'tvg_shift' => (int) ($channel->tvg_shift ?? 0),
                    ],
                ];

                // Get the icon
                $icon = '';
                if ($channel->logo) {
                    // Logo override takes precedence
                    $icon = $channel->logo;
                } elseif ($channel->logo_type === ChannelLogoType::Epg) {
                    $icon = $epgData->icon ?? '';
                } elseif ($channel->logo_type === ChannelLogoType::Channel) {
                    $icon = $channel->logo ?? $channel->logo_internal ?? '';
                }
                if (empty($icon)) {
                    $icon = url('/placeholder.png');
                }
                if ($logoProxyEnabled) {
                    $icon = LogoProxyController::generateProxyUrl($icon);
                }

                // Output the <channel> tag
                echo '  <channel id="'.$tvgId.'">'.PHP_EOL;
                echo '    <display-name lang="'.$epgData->lang.'">'.$title.'</display-name>';
                if ($channelNo !== null) {
                    echo '    <display-name>'.$channelNo.'</display-name>';
                }
                if ($icon) {
                    echo PHP_EOL.'    <icon src="'.$this->escapeXml($icon).'"/>';
                }
                echo PHP_EOL.'  </channel>'.PHP_EOL;
            } elseif ($dummyEpgEnabled) {
                // Get the icon
                $icon = $channel->logo ?? $channel->logo_internal ?? '';
                if (empty($icon)) {
                    $icon = url('/placeholder.png');
                }
                if ($logoProxyEnabled) {
                    $icon = LogoProxyController::generateProxyUrl($icon);
                }
                $icon = $this->escapeXml($icon);

                // Resolve dummy EPG display title using the configured fallback order.
                // Each method is tried in order; the first non-empty value wins.
                // When no order is configured, fall back to title_custom ?? title.
                $dummyTitle = null;
                foreach ($dummyEpgFallbackOrder as $fallbackMethod) {
                    $dummyTitle = match ($fallbackMethod) {
                        'title' => $channel->title_custom ?? $channel->title,
                        'name' => $channel->name_custom ?? $channel->name,
                        'stream_id' => $channel->stream_id_custom ?? $channel->source_id ?? $channel->stream_id,
                        'number' => $channelNo ? (string) $channelNo : '',
                        default => null,
                    };
                    if (! empty($dummyTitle)) {
                        break;
                    }
                }
                $dummyTitle ??= $channel->title_custom ?? $channel->title;
                $dummyTitleEscaped = $this->escapeXml($dummyTitle);

                // Keep track of which channels need a dummy EPG program
                // Need this to output the <programme> tags later
                $dummyEpgChannels[] = [
                    'tvg_id' => $tvgId,
                    'channel_id' => $channel->id,
                    'channel_no' => $channelNo,
                    'title' => $dummyTitleEscaped,
                    'raw_title' => $channel->title_custom ?? $channel->title,
                    'icon' => $icon,
                    'group' => $channel->group ?? $channel->group_internal,
                    'include_category' => $playlist->dummy_epg_category,
                    'aed_profile_id' => $aedProfileId,
                ];

                // Output the <channel> tag
                echo '  <channel id="'.$tvgId.'">'.PHP_EOL;
                echo '    <display-name>'.$dummyTitleEscaped.'</display-name>';
                if ($channelNo !== null) {
                    echo PHP_EOL.'    <display-name>'.$channelNo.'</display-name>';
                }
                if ($icon) {
                    echo PHP_EOL.'    <icon src="'.$icon.'"/>';
                }
                echo PHP_EOL.'  </channel>'.PHP_EOL;
            }
        }

        // Network channels are now included in the regular channel loop above
        // (they are real Channel records with network_id set)
        // We'll output their programmes after regular EPG programmes

        // Fetch the EPGs (channels are keyed by EPG ID)
        $epgs = Epg::whereIn('id', array_keys($epgChannels))
            ->get();

        // Initialize cache service
        $cacheService = new EpgCacheService;

        // Loop through the EPGs and output the <programme> tags
        foreach ($epgs as $epg) {
            // Channel data
            $channels = $epgChannels[$epg->id];

            // Skip if no channels
            if (! count($channels)) {
                continue;
            }

            try {
                // Try to use cached data first with proper validation
                // CRITICAL: Check both is_cached flag AND that cache is actually valid
                // This prevents race condition where cache is being regenerated
                if ($epg->is_cached && $cacheService->isCacheValid($epg)) {
                    // Get all programmes from cache
                    $startDate = Carbon::now()->subDays(1)->format('Y-m-d');
                    $epgDays = config('dev.default_epg_days', 7);
                    $epgDays = is_numeric($epgDays) && $epgDays > 0 ? (int) $epgDays : 7;
                    $endDate = Carbon::now()
                        ->addDays($epgDays)
                        ->format('Y-m-d');

                    // Get all channel IDs that this EPG should map to
                    $epgChannelIds = [];
                    foreach ($channels as $channelMapping) {
                        $epgChannelIds = array_merge($epgChannelIds, array_keys($channelMapping));
                    }

                    // Get programmes from cache for date range
                    $cachedProgrammes = $cacheService->getCachedProgrammesRange($epg, $startDate, $endDate, $epgChannelIds);

                    // Pre-build channel mapping index for O(1) lookups
                    $channelMapping = [];
                    foreach ($channels as $channelMap) {
                        foreach ($channelMap as $epgChannelId => $mappedData) {
                            if (! isset($channelMapping[$epgChannelId])) {
                                $channelMapping[$epgChannelId] = [];
                            }
                            $channelMapping[$epgChannelId][] = $mappedData;
                        }
                    }

                    // Output programmes from cache
                    foreach ($cachedProgrammes as $channelId => $programmes) {
                        // Skip if no mapping for this channel
                        if (! isset($channelMapping[$channelId])) {
                            continue;
                        }

                        foreach ($programmes as $programme) {
                            foreach ($channelMapping[$channelId] as $mappedData) {
                                $mappedChannelId = $mappedData['tvg_id'];
                                $tvgShift = $mappedData['tvg_shift'];

                                // Apply tvg_shift offset to programme times if set
                                if ($tvgShift !== 0) {
                                    $start = Carbon::parse($programme['start'])->addHours($tvgShift)->format('YmdHis O');
                                    $stop = Carbon::parse($programme['stop'])->addHours($tvgShift)->format('YmdHis O');
                                } else {
                                    $start = $this->formatXmltvDateTime($programme['start']);
                                    $stop = $this->formatXmltvDateTime($programme['stop']);
                                }

                                // Build programme XML in buffer for batch output
                                $progXml = '  <programme channel="'.$this->escapeXml($mappedChannelId).'"';
                                if ($start) {
                                    $progXml .= ' start="'.$start.'"';
                                }
                                if ($stop) {
                                    $progXml .= ' stop="'.$stop.'"';
                                }
                                $progXml .= '>'.PHP_EOL;

                                if ($programme['title']) {
                                    $progXml .= '    <title>'.$this->escapeXml($programme['title']).'</title>'.PHP_EOL;
                                }
                                if ($programme['subtitle']) {
                                    $progXml .= '    <sub-title>'.$this->escapeXml($programme['subtitle']).'</sub-title>'.PHP_EOL;
                                }
                                if ($programme['desc']) {
                                    $progXml .= '    <desc>'.$this->escapeXml($programme['desc']).'</desc>'.PHP_EOL;
                                }
                                if ($programme['category']) {
                                    $progXml .= '    <category>'.$this->escapeXml($programme['category']).'</category>'.PHP_EOL;
                                }
                                foreach (EpisodeNumberNormalizer::forProgramme($programme) as $episodeNumber) {
                                    $systemAttribute = ($episodeNumber['system'] !== null && $episodeNumber['system'] !== '')
                                        ? ' system="'.$this->escapeXml($episodeNumber['system']).'"'
                                        : '';
                                    $progXml .= '    <episode-num'.$systemAttribute.'>'.$this->escapeXml($episodeNumber['value']).'</episode-num>'.PHP_EOL;
                                }
                                if ($programme['icon']) {
                                    $icon = $logoProxyEnabled
                                        ? LogoProxyController::generateProxyUrl($programme['icon'])
                                        : $programme['icon'];
                                    $progXml .= '    <icon src="'.$this->escapeXml($icon).'"/>'.PHP_EOL;
                                }
                                // Program artwork images (NEW)
                                if (! empty($programme['images'] ?? null) && is_array($programme['images'])) {
                                    foreach ($programme['images'] as $image) {
                                        $rawUrl = $image['url'] ?? '';
                                        $proxiedUrl = $logoProxyEnabled && $rawUrl
                                            ? LogoProxyController::generateProxyUrl($rawUrl)
                                            : $rawUrl;

                                        $url = $this->escapeXml($proxiedUrl);
                                        $type = $this->escapeXml($image['type']);
                                        $width = $this->escapeXml($image['width']);
                                        $height = $this->escapeXml($image['height']);
                                        $orient = $this->escapeXml($image['orient']);
                                        $size = $this->escapeXml($image['size']);

                                        $progXml .= "    <icon src=\"{$url}\" type=\"{$type}\" width=\"{$width}\" height=\"{$height}\" orient=\"{$orient}\" size=\"{$size}\" />\n";
                                    }
                                }
                                if ($programme['rating']) {
                                    $progXml .= '    <rating><value>'.$this->escapeXml($programme['rating']).'</value></rating>'.PHP_EOL;
                                }
                                if (! empty($programme['new']) && $programme['new']) {
                                    $progXml .= '    <new />'.PHP_EOL;
                                }

                                $progXml .= '  </programme>'.PHP_EOL;
                                echo $progXml;
                            }
                        }
                    }
                } else {
                    // Fallback to original XML reading if cache is not available
                    $this->processEpgWithXmlReader($epg, $channels, $playlist);
                }
            } catch (Exception $e) {
                // If cache fails, fallback to original XML reading
                try {
                    $this->processEpgWithXmlReader($epg, $channels, $playlist);
                } catch (Exception $fallbackException) {
                    Log::warning("EPG fallback XMLReader also failed for EPG {$epg->name}: {$fallbackException->getMessage()}");
                }
            }
        }

        // If dummy EPG channels, generate dummy programmes
        if (count($dummyEpgChannels) > 0) {
            // Pre-calculate standard repeating time slots once (used for non-AED channels)
            $timeSlots = [];
            $startTime = Carbon::now()->startOf('day')->subMinutes($dummyEpgLength);
            $iterations = (int) ((5 * 24 * 60) / $dummyEpgLength);

            for ($i = 0; $i < $iterations; $i++) {
                $startTime->addMinutes($dummyEpgLength);
                $timeSlots[] = [
                    'start' => str_replace(':', '', $startTime->format('YmdHis P')),
                    'end' => str_replace(':', '', $startTime->copy()->addMinutes($dummyEpgLength)->format('YmdHis P')),
                ];
            }

            // Bulk-load all AED profiles referenced by any dummy channel (avoids N+1)
            $aedProfileIds = array_filter(array_unique(
                array_column($dummyEpgChannels, 'aed_profile_id')
            ));
            $aedProfiles = count($aedProfileIds)
                ? AedProfile::whereIn('id', $aedProfileIds)->get()->keyBy('id')
                : collect();
            $aedExtractor = count($aedProfileIds) ? app(AedExtractorService::class) : null;

            // Generate programmes for each channel using pre-calculated time slots
            foreach ($dummyEpgChannels as $dummyEpgChannel) {
                $tvgId = $this->escapeXml($dummyEpgChannel['tvg_id']);
                $title = $dummyEpgChannel['title'];
                $group = $this->escapeXml($dummyEpgChannel['group']);
                $includeCategory = $dummyEpgChannel['include_category'];
                $aedProfileId = $dummyEpgChannel['aed_profile_id'] ?? null;

                $buffer = '';

                // AED path: extract event info from stream title and generate a single event
                if ($aedProfileId && $aedExtractor && $aedProfiles->has($aedProfileId)) {
                    $aedProfile = $aedProfiles->get($aedProfileId);
                    $rawTitle = $dummyEpgChannel['raw_title'];
                    $aedEvent = $aedExtractor->extract($aedProfile, $rawTitle)
                        ?? $aedExtractor->fallback($aedProfile, $rawTitle);

                    $aedIcon = $aedProfile->logo_url
                        ? $this->escapeXml($aedProfile->logo_url)
                        : null;
                    $aedCategory = $aedProfile->category
                        ? $this->escapeXml($aedProfile->category)
                        : ($includeCategory ? $group : null);

                    if ($aedEvent->hasTime()) {
                        $aedTitle = $this->escapeXml($aedEvent->title);
                        $aedDesc = $aedEvent->description
                            ? $this->escapeXml($aedEvent->description)
                            : $aedTitle;

                        $slotMinutes = $aedProfile->event_duration_minutes;
                        $windowStart = Carbon::now()->startOfDay();
                        $windowEnd = Carbon::now()->startOfDay()->addDays(5);
                        $postTitle = $aedExtractor->postEventTitle($aedProfile, $rawTitle, $aedEvent);
                        $postTitleEscaped = $postTitle !== null ? $this->escapeXml($postTitle) : null;

                        $emitSlot = function (string $slotTitle, Carbon $slotStart, Carbon $slotEnd) use (&$buffer, $tvgId, $aedIcon, $aedCategory): void {
                            $s = str_replace(':', '', $slotStart->format('YmdHis P'));
                            $e = str_replace(':', '', $slotEnd->format('YmdHis P'));
                            $buffer .= '  <programme channel="'.$tvgId.'" start="'.$s.'" stop="'.$e.'">'.PHP_EOL;
                            $buffer .= '    <title>'.$slotTitle.'</title>'.PHP_EOL;
                            if ($aedIcon) {
                                $buffer .= '    <icon src="'.$aedIcon.'"/>'.PHP_EOL;
                            }
                            $buffer .= '    <desc>'.$slotTitle.'</desc>'.PHP_EOL;
                            if ($aedCategory) {
                                $buffer .= '    <category lang="en">'.$aedCategory.'</category>'.PHP_EOL;
                            }
                            $buffer .= '  </programme>'.PHP_EOL;
                        };

                        // Pre-event fill: window start → event start (skipped when pre_event_format is null)
                        $cursor = $windowStart->copy();
                        while ($cursor->lt($aedEvent->start)) {
                            $slotEnd = $cursor->copy()->addMinutes($slotMinutes);
                            if ($slotEnd->gt($aedEvent->start)) {
                                $slotEnd = $aedEvent->start->copy();
                            }
                            $preTitle = $aedExtractor->preEventTitle($aedProfile, $rawTitle, $aedEvent, $cursor);
                            if ($preTitle !== null) {
                                $emitSlot($this->escapeXml($preTitle), $cursor, $slotEnd);
                            }
                            $cursor = $slotEnd;
                        }

                        // The event itself
                        $start = str_replace(':', '', $aedEvent->start->format('YmdHis P'));
                        $stop = str_replace(':', '', $aedEvent->end->format('YmdHis P'));
                        $buffer .= '  <programme channel="'.$tvgId.'" start="'.$start.'" stop="'.$stop.'">'.PHP_EOL;
                        $buffer .= '    <title>'.$aedTitle.'</title>'.PHP_EOL;
                        if ($aedIcon) {
                            $buffer .= '    <icon src="'.$aedIcon.'"/>'.PHP_EOL;
                        }
                        $buffer .= '    <desc>'.$aedDesc.'</desc>'.PHP_EOL;
                        if ($aedCategory) {
                            $buffer .= '    <category lang="en">'.$aedCategory.'</category>'.PHP_EOL;
                        }
                        $buffer .= '  </programme>'.PHP_EOL;

                        // Post-event fill: event end → window end (skipped when post_event_format is null)
                        if ($postTitleEscaped !== null) {
                            $cursor = $aedEvent->end->copy();
                            while ($cursor->lt($windowEnd)) {
                                $slotEnd = $cursor->copy()->addMinutes($slotMinutes);
                                if ($slotEnd->gt($windowEnd)) {
                                    $slotEnd = $windowEnd->copy();
                                }
                                $emitSlot($postTitleEscaped, $cursor, $slotEnd);
                                $cursor = $slotEnd;
                            }
                        }
                    } else {
                        // Extraction failed or no time - use AED title with standard repeating slots
                        $aedTitle = $this->escapeXml($aedEvent->title);
                        $aedDesc = $aedEvent->description
                            ? $this->escapeXml($aedEvent->description)
                            : $aedTitle;
                        $aedSlotLength = $aedProfile->event_duration_minutes;
                        $aedStart = Carbon::now()->startOf('day')->subMinutes($aedSlotLength);
                        $aedIterations = (int) ((5 * 24 * 60) / $aedSlotLength);

                        for ($i = 0; $i < $aedIterations; $i++) {
                            $aedStart->addMinutes($aedSlotLength);
                            $start = str_replace(':', '', $aedStart->format('YmdHis P'));
                            $stop = str_replace(':', '', $aedStart->copy()->addMinutes($aedSlotLength)->format('YmdHis P'));

                            $buffer .= '  <programme channel="'.$tvgId.'" start="'.$start.'" stop="'.$stop.'">'.PHP_EOL;
                            $buffer .= '    <title>'.$aedTitle.'</title>'.PHP_EOL;
                            if ($aedIcon) {
                                $buffer .= '    <icon src="'.$aedIcon.'"/>'.PHP_EOL;
                            }
                            $buffer .= '    <desc>'.$aedDesc.'</desc>'.PHP_EOL;
                            if ($aedCategory) {
                                $buffer .= '    <category lang="en">'.$aedCategory.'</category>'.PHP_EOL;
                            }
                            $buffer .= '  </programme>'.PHP_EOL;
                        }
                    }
                } else {
                    // Standard dummy EPG: repeating slots using the channel title
                    foreach ($timeSlots as $slot) {
                        $buffer .= '  <programme channel="'.$tvgId.'" start="'.$slot['start'].'" stop="'.$slot['end'].'">'.PHP_EOL;
                        $buffer .= '    <title>'.$title.'</title>'.PHP_EOL;
                        $buffer .= '    <desc>'.$title.'</desc>'.PHP_EOL;
                        if ($includeCategory) {
                            $buffer .= '    <category lang="en">'.$group.'</category>'.PHP_EOL;
                        }
                        $buffer .= '  </programme>'.PHP_EOL;
                    }
                }

                // Single echo per channel instead of multiple echoes
                echo $buffer;
            }
        }

        // Output Network programme schedules (from channels with network_id)
        if (! empty($networkChannelIds)) {
            $networks = Network::whereIn('id', array_keys($networkChannelIds))
                ->with(['programmes' => function ($q) {
                    $q->where('end_time', '>', Carbon::now()->subDay())
                        ->orderBy('start_time');
                }])
                ->get();

            foreach ($networks as $network) {
                $tvgId = $networkChannelIds[$network->id];

                foreach ($network->programmes as $programme) {
                    $start = str_replace(':', '', $programme->start_time->format('YmdHis O'));
                    $stop = str_replace(':', '', $programme->end_time->format('YmdHis O'));
                    $title = $this->escapeXml($programme->title);
                    $desc = $programme->description ? $this->escapeXml($programme->description) : '';
                    $icon = $programme->image ? $this->escapeXml($programme->image) : '';
                    $category = $programme->contentable_type === 'App\\Models\\Episode' ? 'Series' : 'Movie';

                    echo '  <programme channel="'.$this->escapeXml($tvgId).'" start="'.$start.'" stop="'.$stop.'">'.PHP_EOL;
                    echo '    <title>'.$title.'</title>'.PHP_EOL;
                    if ($desc) {
                        echo '    <desc>'.$desc.'</desc>'.PHP_EOL;
                    }
                    if ($icon) {
                        echo '    <icon src="'.$icon.'"/>'.PHP_EOL;
                    }
                    echo '    <category>'.$category.'</category>'.PHP_EOL;
                    echo '  </programme>'.PHP_EOL;
                }
            }
        }

        // Close it out
        echo '</tv>';
    }

    /**
     * Check if cache file is valid and not expired
     */
    private function isCacheValid($playlist, bool $compressed = false): bool
    {
        $cacheFilePath = EpgCacheService::getPlaylistEpgCachePath($playlist, $compressed);
        $disk = Storage::disk('local');

        if (! $disk->exists($cacheFilePath)) {
            return false;
        }

        // Check if file is older than TTL
        $cacheFileTime = $disk->lastModified($cacheFilePath);
        $expiryTime = now()->subHours(self::CACHE_TTL_HOURS)->timestamp;

        return $cacheFileTime >= $expiryTime;
    }

    /**
     * Serve cached file directly
     */
    private function serveCachedFile($playlist, bool $compressed = false)
    {
        $cacheFilePath = EpgCacheService::getPlaylistEpgCachePath($playlist, $compressed);
        $disk = Storage::disk('local');

        $filename = Str::slug($playlist->name).($compressed ? '.xml.gz' : '.xml');
        $contentType = $compressed ? 'application/gzip' : 'application/xml';

        return response()->stream(
            function () use ($disk, $cacheFilePath) {
                $stream = $disk->readStream($cacheFilePath);
                fpassthru($stream);
                fclose($stream);
            },
            200,
            [
                'Access-Control-Allow-Origin' => '*',
                'Cache-Control' => 'no-store, no-cache, must-revalidate',
                'Content-Disposition' => "attachment; filename=\"$filename\"",
                'Content-Type' => $contentType,
                'X-EPG-Cache' => 'HIT',
            ]
        );
    }

    /**
     * Generate and cache EPG file
     */
    private function generateAndCache($playlist, bool $compressed = false)
    {
        $cacheFilePath = EpgCacheService::getPlaylistEpgCachePath($playlist, $compressed);
        $disk = Storage::disk('local');

        // Ensure cache directory exists
        $cacheDir = dirname($cacheFilePath);
        if (! $disk->exists($cacheDir)) {
            $disk->makeDirectory($cacheDir, 0755, true);
        }

        $filename = Str::slug($playlist->name).($compressed ? '.xml.gz' : '.xml');
        $contentType = $compressed ? 'application/gzip' : 'application/xml';

        if ($compressed) {
            // For compressed, keep existing behaviour (generate then compress)
            // NOTE: streaming gzip on-the-fly is more complex; keep as-is for safety
            ob_start();
            $this->generate($playlist);
            $content = ob_get_clean();
            $compressedContent = gzencode($content, 9);

            // Save to cache
            $disk->put($cacheFilePath, $compressedContent);

            return response($compressedContent, 200, [
                'Access-Control-Allow-Origin' => '*',
                'Cache-Control' => 'no-store, no-cache, must-revalidate',
                'Content-Disposition' => "attachment; filename=\"$filename\"",
                'Content-Type' => $contentType,
                'X-EPG-Cache' => 'MISS',
            ]);
        }

        // For regular XML, stream generation directly to the client and write cache incrementally
        return response()->stream(function () use ($playlist, $disk, $cacheFilePath) {
            // Resolve full path for cache and ensure directory exists
            $fullPath = $disk->path($cacheFilePath);
            $dir = dirname($fullPath);
            if (! is_dir($dir)) {
                @mkdir($dir, 0755, true);
            }

            $tmpPath = $fullPath.'.tmp';
            $fh = null;
            $completed = false;

            // Register a shutdown handler to remove the temp file if generation did not complete
            $cleanupShutdown = function () use (&$completed, &$fh, $tmpPath, $dir) {
                try {
                    if (! $completed) {
                        if (is_resource($fh)) {
                            @fclose($fh);
                        }
                        if (file_exists($tmpPath)) {
                            @unlink($tmpPath);
                        }
                    }

                    // Also cleanup stale tmp files to avoid orphans
                    foreach (glob($dir.'/*.tmp') as $f) {
                        try {
                            @unlink($f);
                        } catch (\Throwable $e) {
                            // ignore
                        }
                    }
                } catch (\Throwable $e) {
                    // ignore shutdown cleanup errors
                }
            };
            register_shutdown_function($cleanupShutdown);

            $fh = @fopen($tmpPath, 'w');
            if ($fh === false) {
                // Fallback: if we can't write cache, just stream without caching
                $this->generate($playlist);

                return;
            }

            // Start an output buffer with a callback that writes each flushed chunk to cache
            ob_start(function ($buffer) use ($fh) {
                // Write chunk to cache file
                @fwrite($fh, $buffer);

                // Return buffer so it is sent to the client
                return $buffer;
            }, 4096);

            try {
                // Generate will echo directly; each echo will be passed through the ob callback
                $this->generate($playlist);

                // Mark completed only after successful generation
                $completed = true;

                // Flush any remaining buffers
                while (ob_get_level() > 0) {
                    ob_end_flush();
                }
            } finally {
                // Ensure file handle closed and atomically move temp to final path only on success
                if (is_resource($fh)) {
                    fclose($fh);
                }
                if ($completed) {
                    @rename($tmpPath, $fullPath);
                } else {
                    if (file_exists($tmpPath)) {
                        @unlink($tmpPath);
                    }
                }
            }
        }, 200, [
            'Access-Control-Allow-Origin' => '*',
            'Cache-Control' => 'no-store, no-cache, must-revalidate',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
            'Content-Type' => $contentType,
            'X-EPG-Cache' => 'MISS',
        ]);
    }

    /**
     * Gzip the file
     *
     * @param  string  $filename
     * @param  string  $disk
     * @param  bool  $delete_original
     * @return bool
     */
    private function gzip($filename, $disk = 'local', $delete_original = false)
    {
        $disk = Storage::disk($disk);
        $data = $disk->get($filename);
        $out_file = "$filename.gz";

        $gzdata = gzencode($data, 9);
        $disk->put($out_file, $gzdata);
        $fp = fopen($disk->path($out_file), 'w');
        $result = fwrite($fp, $gzdata);
        fclose($fp);

        if ($result && $delete_original) {
            $disk->delete($filename);
        }

        return $result > 0;
    }

    /**
     * Format datetime for XMLTV format
     *
     * @param  string  $datetime  ISO 8601 datetime string
     * @return string|null XMLTV formatted datetime
     */
    private function formatXmltvDateTime($datetime)
    {
        if (! $datetime) {
            return null;
        }

        try {
            $carbon = Carbon::parse($datetime);

            // Format as YYYYMMDDHHMMSS +ZZZZ
            return $carbon->format('YmdHis O');
        } catch (Exception $e) {
            return null;
        }
    }

    /**
     * Process EPG using XMLReader (fallback method)
     *
     * @param  Epg  $epg
     * @param  array  $channels
     * @param  mixed  $playlist
     */
    private function processEpgWithXmlReader($epg, $channels, $playlist)
    {
        // Get the content
        $filePath = null;
        if ($epg->url && str_starts_with($epg->url, 'http')) {
            $localPath = Storage::disk('local')->path($epg->file_path);
            if (! file_exists($localPath)) {
                Log::warning("EPG source file not found on disk for EPG \"{$epg->name}\": {$localPath}");

                return;
            }
            $filePath = $localPath;
        } elseif ($epg->uploads && Storage::disk('local')->exists($epg->uploads)) {
            $filePath = Storage::disk('local')->path($epg->uploads);
        } elseif ($epg->url) {
            $filePath = $epg->url;
        }

        if (! $filePath) {
            // Send notification
            $error = 'Invalid EPG file. Unable to read or download an associated EPG file. Please check the URL or uploaded file and try again.';
            Notification::make()
                ->danger()
                ->title("Error generating epg data for playlist \"{$playlist->name}\" using EPG \"{$epg->name}\"")
                ->body($error)
                ->broadcast($epg->user);
            Notification::make()
                ->danger()
                ->title("Error generating epg data for playlist \"{$playlist->name}\" using EPG \"{$epg->name}\"")
                ->body($error)
                ->sendToDatabase($epg->user);

            return;
        }

        // Set up the reader
        $programReader = new XMLReader;
        if (! @$programReader->open('compress.zlib://'.$filePath)) {
            Log::warning("Failed to open EPG file for XMLReader: {$filePath}");

            return;
        }

        // Loop through the XML data
        while (@$programReader->read()) {
            // Only consider XML elements and programme nodes
            if ($programReader->nodeType == XMLReader::ELEMENT && $programReader->name === 'programme') {
                // Get the channel id
                $channelId = trim($programReader->getAttribute('channel'));
                if (! $channelId) {
                    continue;
                }

                // EPG could be applied to multiple channels, find all matching channels
                $filtered = array_filter($channels, fn ($ch) => array_key_exists($channelId, $ch));
                if (! count($filtered)) {
                    continue;
                }
                // Channel program found, output the <programme> tag
                // First, we need to make sure the channel is correct
                // Replace `channel="<channel_id>"` with `channel="<stream_id>"`
                $itemDom = new DOMDocument;
                $itemDom->loadXML($programReader->readOuterXML());

                // Get the item element
                $item = $itemDom->documentElement;
                $this->normalizeEpisodeNumbers($item);

                // Save original time attributes before the loop so each iteration starts fresh
                $originalStart = $item->getAttribute('start');
                $originalStop = $item->getAttribute('stop');

                foreach ($filtered as $ch) {
                    $mappedData = $ch[$channelId];
                    $tvgShift = $mappedData['tvg_shift'];

                    // Modify the channel attribute
                    $item->setAttribute('channel', $mappedData['tvg_id']);

                    // Apply tvg_shift to start/stop times if set
                    if ($tvgShift !== 0) {
                        if ($originalStart) {
                            try {
                                $shifted = Carbon::parse($originalStart)->addHours($tvgShift);
                                $item->setAttribute('start', str_replace(':', '', $shifted->format('YmdHis O')));
                            } catch (Exception $e) {
                                $item->setAttribute('start', $originalStart);
                            }
                        }

                        if ($originalStop) {
                            try {
                                $shifted = Carbon::parse($originalStop)->addHours($tvgShift);
                                $item->setAttribute('stop', str_replace(':', '', $shifted->format('YmdHis O')));
                            } catch (Exception $e) {
                                $item->setAttribute('stop', $originalStop);
                            }
                        }
                    } else {
                        // Restore original times (in case a previous iteration applied a shift)
                        $item->setAttribute('start', $originalStart);
                        $item->setAttribute('stop', $originalStop);
                    }

                    // Output modified line
                    echo '  '.$itemDom->saveXML($item).PHP_EOL;
                }
            }
        }
        // Close the XMLReader for this epg
        $programReader->close();
    }

    private function normalizeEpisodeNumbers(DOMElement $programme): void
    {
        $episodeNumberElements = [];

        foreach ($programme->childNodes as $childNode) {
            if ($childNode instanceof DOMElement && $childNode->tagName === 'episode-num') {
                $episodeNumberElements[] = $childNode;
            }
        }

        foreach ($episodeNumberElements as $episodeNumberElement) {
            $normalizedEpisodeNumbers = EpisodeNumberNormalizer::normalize([[
                'system' => $episodeNumberElement->hasAttribute('system')
                    ? $episodeNumberElement->getAttribute('system')
                    : null,
                'value' => $episodeNumberElement->textContent,
            ]]);

            if ($normalizedEpisodeNumbers === []) {
                $programme->removeChild($episodeNumberElement);

                continue;
            }

            $episodeNumberElement->textContent = $normalizedEpisodeNumbers[0]['value'];
        }
    }

    /**
     * Generate EPG for a network playlist (outputs network programme schedules).
     */
    protected function generateNetworkPlaylistEpg(Playlist $playlist)
    {
        $networks = $playlist->networks()
            ->where('enabled', true)
            ->get();

        if ($networks->isEmpty()) {
            return response('<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv generator-info-name="M3U Editor Networks">
<!-- No networks assigned to this playlist -->
</tv>', 200, [
                'Content-Type' => 'application/xml',
            ]);
        }

        $epgService = app(NetworkEpgService::class);

        return response()->stream(function () use ($networks, $epgService) {
            $epgService->streamXmltvForNetworks($networks);
        }, 200, [
            'Content-Type' => 'application/xml',
            'Content-Disposition' => 'inline; filename="epg.xml"',
            'Cache-Control' => 'no-cache, no-store, must-revalidate',
        ]);
    }
}
